version: '3.8'

services:
  ryms-db:
    image: postgres:17
    container_name: ryms-db
    restart: always

    environment:
      POSTGRES_USER: ryms
      POSTGRES_PASSWORD: ryms
      POSTGRES_DB: ryms-database

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - ryms-volume:/var/lib/postgresql/data
      
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  ryms-volume:
    driver: local